# Generated by Django 4.1.3 on 2022-12-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_secalculaengramos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoContable',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productos.producto')),
            ],
            bases=('productos.producto',),
        ),
        migrations.CreateModel(
            name='ProductoEnGramos',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productos.producto')),
            ],
            bases=('productos.producto',),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='seCalculaEnGramos',
        ),
    ]
