# Generated by Django 4.1.3 on 2022-12-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changoxproducto',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
