# Generated by Django 4.1.3 on 2022-12-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_alter_changoxproducto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chango',
            old_name='fechaCreacion',
            new_name='fechaHoraCreacion',
        ),
        migrations.RenameField(
            model_name='chango',
            old_name='fechaPago',
            new_name='fechaHoraPago',
        ),
    ]
