# Generated by Django 4.1.3 on 2022-12-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_alter_changoxproducto_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chango',
            old_name='fechaHoraPago',
            new_name='fechaHoraCierre',
        ),
        migrations.RemoveField(
            model_name='chango',
            name='fuePagado',
        ),
    ]
